# Basis-Image
FROM python:3.9-slim

# Arbeitsverzeichnis
WORKDIR /app


COPY requirements_streamlit.txt ./

# Abhängigkeiten installieren
RUN pip install --no-cache-dir -r requirements.txt

# Restliche Dateien kopieren
COPY . .

# Port (für Streamlit)
EXPOSE 8501

# Startbefehl für Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
