# Basis-Image
FROM python:3.11-slim

# System-Pakete installieren
RUN apt-get update && \
    apt-get install -y build-essential libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Arbeitsverzeichnis
WORKDIR /app

# Requirements kopieren & installieren
COPY requirements_cron.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements_cron.txt

# Projektdateien kopieren
COPY . .

# Falls du sofort ausführen möchtest (z. B. beim Start Container)
CMD ["python", "osw_api_2_db.py"]