name: Selenium Download

on:
  schedule:
    - cron: '*/5 * * * *'  # Läuft täglich um 12:00 Uhr UTC
  workflow_dispatch:  # Ermöglicht manuelles Starten

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4


      - name: Installiere Python-Abhängigkeiten
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      #- name: Set executable permission for chromedriver
        #run: chmod +x ./.github/workflows/chromedriver

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Download ChromeDriver 133
        run: |
          # Lade die Version 133 des ChromeDrivers herunter
          wget https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.126/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      - name: Verify ChromeDriver installation
        run: chromedriver --version

      - name: Starte Selenium-Skript
        run: python test.py
        env:
          DISPLAY: :99

      - name: Füge die heruntergeladene Datei hinzu und pushe sie ins Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Neue Datei von Selenium-Download hinzugefügt" || echo "Nichts zu committen"
          git push
