name: Install ChromeDriver 133

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-chromedriver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Download ChromeDriver 133
        run: |
          # Lade die Version 133 des ChromeDrivers herunter
          wget https://storage.googleapis.com/chrome-for-testing-public/133.0.6943.126/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      - name: Verify ChromeDriver installation
        run: chromedriver --version
